### ISSUE TITLE
var and std

### ISSUE THREAD

**Issue by m0yoshimura** [cuiziteng/ICCV_MAET#7]
Hi! Thank you very much for sharing the great work.

Why you insert variation in the std parameter?
https://github.com/cuiziteng/ICCV_MAET/blob/5fe75784ab058e22a8f595d0a26bdfc6d4cdd5c5/mmdet/models/detectors/MAET_YOLO/MAET_YOLO.py#L217
I read original imprementation of 'unprocessing' and it's different. 
This repo seems to estimate noise level smaller than original repo.

Also, why quantization noise can be bellow? https://github.com/cuiziteng/ICCV_MAET/blob/5fe75784ab058e22a8f595d0a26bdfc6d4cdd5c5/mmdet/models/detectors/MAET_YOLO/MAET_YOLO.py#L225
I think quantization noise is related to the value of 2**bits.

Thank you in advance!

**Comment by cuiziteng** [comment]
Hi !
1. This is same. Because the work "Un-process" they use a specific cameras' settings, and there remain difference between low-light and normal-light condition, so here we don't need to obey them.

2. We take a uniform distribution for simulate quantisation noise ([link](https://www.sciencedirect.com/topics/engineering/quantization-noise)), the quantization in real ISPs is 16-bit to 8-bit, and. And you can see [this line](https://github.com/cuiziteng/ICCV_MAET/blob/5fe75784ab058e22a8f595d0a26bdfc6d4cdd5c5/configs/MAET_yolo/maet_yolo_coco_ort.py#L47).  here we take 3 number between 8~16.

**Comment by m0yoshimura** [comment]
Thank you for quick modification!

I can understand the ([link](https://www.sciencedirect.com/topics/engineering/quantization-noise)) but it saids that, quantizaiton noise is
`uniform(-Δ/2, Δ/2)`
and
`Δ~2^(-bits).
`
So from the link, I think
`uniform(-1/2^(bits+1), 1/2^(bits+1))`
is correct although this difference might not affect the accuracy.
 if bits=12,
 1/3060(=255*12) and 1/8292(=2^(12+1))
 if bits=16,
 1/4080(=255*16) and 1/131072(=2^(16+1))

**Comment by m0yoshimura** [comment]
Also, did you use this function? 
https://github.com/cuiziteng/ICCV_MAET/blob/a3f74a54c95316c9f8d98bedb918c47f55f41802/mmdet/datasets/pipelines/dark_transforms.py#L34
`
bits = random.choice(self.quantization)

img_quan1 = img* 255.0

img_quan_bit = img_quan1/ bits  

img_quan2 = np.around(img_quan_bit)* bits  

#quan_noise = (img_quan2 - img_quan1)/ bits  

img = img_quan2/ 255.0
` 
This quantization noise is also diffenrent from the implementation in MAET_YOLO.py and it is too big.
1/bits of domain is occupyed with noise and darkened image has almost no info.

**Comment by cuiziteng** [comment]
Thank you so much, I'll correct it. And also very happy to see your modeling's results!
