### ISSUE TITLE
code of "Linear Array Network for Low-light Image Enhancement"

### ISSUE THREAD

**Issue by zhaoyaxinzyx** [cuiziteng/ICCV_MAET#8]
Dear teacher, I learned a lot from your paper "Linear Array Network for Low-light Image Enhancement", but I found that the code connection published in your paper has not been published. Could you please publish your working code? The student wants to study. Thank you very much

**Comment by cuiziteng** [comment]
Hello, thanks so much for your interest, since the paper Linear Array Network for Low-light Image Enhancement is still under review, I'm not the first author so I have to to ask my co-author for code releasing. 

Another of my work about low-light enhancement is open source: https://github.com/cuiziteng/Illumination-Adaptive-Transformer, the paper is using a transformer for low-light enhancement, you can try it if you interest, thx~
